# Generated by Django 5.1.6 on 2025-03-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_by',
            field=models.CharField(default='UnKnown', max_length=100),
        ),
    ]
