# Generated by Django 5.1.6 on 2025-03-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='created_at',
        ),
    ]
