# Generated by Django 5.1.6 on 2025-03-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_order_date_order_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='order_date',
        ),
        migrations.AddField(
            model_name='order',
            name='seller_name',
            field=models.CharField(default='Unknown Seller', max_length=255),
        ),
    ]
