# Generated by Django 5.1.6 on 2025-03-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('spices', 'Spices'), ('flowers', 'Flowers')], max_length=50),
        ),
    ]
